// src/learningHub.js
// Dedicated content library for the Industry Resource Hub.
// This is intentionally separate from data.js's HUB_CATEGORIES/getQuestions
// (the old "prompt" model) — the Hub is now a learning library, not a
// question-and-answer tool, so it gets its own data shape.
//
// Each category has ~15 curated Learning Topics spanning three levels:
// foundational, growth, advanced. Topics are static/curated; the actual
// Learning Guide content for each topic is generated on demand by AI
// (see askLearningGuide in App.jsx) — nothing educational is hardcoded here.

export const LEARNING_HUB = [
  {
    id: "entrepreneurship",
    num: "01",
    label: "Entrepreneurs & Small Business",
    tagline: "Learn how to build, run, and grow a business — from your first idea to scaling operations.",
    topics: [
      { id:"entrepreneurship-01", title:"Validating a Business Idea", level:"foundational", shortDescription:"How to test whether an idea actually solves a real problem before you invest time and money.", learningObjective:"Understand the core methods for validating demand before building.", relatedTopicIds:["entrepreneurship-02","entrepreneurship-03"] },
      { id:"entrepreneurship-02", title:"Understanding Your Customer", level:"foundational", shortDescription:"The fundamentals of identifying who you're actually building for and what they need.", learningObjective:"Learn how to define and understand a target customer.", relatedTopicIds:["entrepreneurship-01","entrepreneurship-06"] },
      { id:"entrepreneurship-03", title:"Business Models Explained", level:"foundational", shortDescription:"The major ways businesses make money, and how to think about choosing one.", learningObjective:"Understand common business model types and their tradeoffs.", relatedTopicIds:["entrepreneurship-04","entrepreneurship-13"] },
      { id:"entrepreneurship-04", title:"Pricing Fundamentals", level:"foundational", shortDescription:"How to think about setting prices for a product or service.", learningObjective:"Learn the core frameworks for pricing decisions.", relatedTopicIds:["entrepreneurship-03","entrepreneurship-13"] },
      { id:"entrepreneurship-05", title:"Branding vs. Marketing", level:"foundational", shortDescription:"The difference between who you are as a business and how you reach people.", learningObjective:"Understand the distinction and relationship between brand and marketing.", relatedTopicIds:["entrepreneurship-06","entrepreneurship-08"] },
      { id:"entrepreneurship-06", title:"Customer Acquisition Economics", level:"growth", shortDescription:"How to think about what it costs to win a customer versus what they're worth.", learningObjective:"Understand CAC, LTV, and how they guide growth decisions.", relatedTopicIds:["entrepreneurship-02","entrepreneurship-13"] },
      { id:"entrepreneurship-07", title:"Building Repeatable Systems", level:"growth", shortDescription:"How to turn one-off tasks into processes that don't depend on you doing them personally.", learningObjective:"Learn how operational systems reduce founder dependency.", relatedTopicIds:["entrepreneurship-08","entrepreneurship-11"] },
      { id:"entrepreneurship-08", title:"Creating a Sales Process", level:"growth", shortDescription:"How to move a prospect from interest to paying customer in a repeatable way.", learningObjective:"Understand the stages of a basic sales process.", relatedTopicIds:["entrepreneurship-05","entrepreneurship-07"] },
      { id:"entrepreneurship-09", title:"Cash Flow Management", level:"growth", shortDescription:"Why profit and cash are different, and how to avoid running out of money.", learningObjective:"Understand the basics of managing cash flow in a small business.", relatedTopicIds:["entrepreneurship-13","entrepreneurship-14"] },
      { id:"entrepreneurship-10", title:"Hiring Your First Team Members", level:"growth", shortDescription:"What to consider before bringing on your first employee or contractor.", learningObjective:"Understand the key decisions in early hiring.", relatedTopicIds:["entrepreneurship-11","entrepreneurship-14"] },
      { id:"entrepreneurship-11", title:"Scaling Operations", level:"advanced", shortDescription:"What changes when a business grows beyond what one person can manage directly.", learningObjective:"Understand the operational shifts required to scale.", relatedTopicIds:["entrepreneurship-07","entrepreneurship-12"] },
      { id:"entrepreneurship-12", title:"Strategic Planning for Founders", level:"advanced", shortDescription:"How experienced founders set direction and prioritize over multi-year horizons.", learningObjective:"Learn frameworks for longer-term business strategy.", relatedTopicIds:["entrepreneurship-11","entrepreneurship-15"] },
      { id:"entrepreneurship-13", title:"Unit Economics", level:"advanced", shortDescription:"How to evaluate whether a business model is actually profitable at the unit level.", learningObjective:"Understand how to analyze margin and profitability per unit or customer.", relatedTopicIds:["entrepreneurship-06","entrepreneurship-09"] },
      { id:"entrepreneurship-14", title:"Partnerships and Business Development", level:"advanced", shortDescription:"How strategic partnerships are structured and what makes them valuable.", learningObjective:"Understand how partnerships can accelerate growth.", relatedTopicIds:["entrepreneurship-10","entrepreneurship-15"] },
      { id:"entrepreneurship-15", title:"Preparing a Business for Investment or Acquisition", level:"advanced", shortDescription:"What investors and acquirers actually look for when evaluating a business.", learningObjective:"Understand the fundamentals of investment and acquisition readiness.", relatedTopicIds:["entrepreneurship-12","entrepreneurship-13"] },
    ],
  },
  {
    id: "corporate",
    num: "02",
    label: "Corporate & Leadership",
    tagline: "Learn how organizations work, and how to lead, manage, and grow within them.",
    topics: [
      { id:"corporate-01", title:"How Corporate Organizations Work", level:"foundational", shortDescription:"The basic structures and functions that make up a typical company.", learningObjective:"Understand how corporate organizations are typically structured.", relatedTopicIds:["corporate-02","corporate-11"] },
      { id:"corporate-02", title:"Understanding Org Charts and Reporting Lines", level:"foundational", shortDescription:"How authority, reporting, and decision-making are typically organized.", learningObjective:"Learn to read and understand organizational hierarchy.", relatedTopicIds:["corporate-01","corporate-11"] },
      { id:"corporate-03", title:"Professional Communication Fundamentals", level:"foundational", shortDescription:"How to communicate clearly and appropriately in a professional environment.", learningObjective:"Understand core principles of workplace communication.", relatedTopicIds:["corporate-08","corporate-09"] },
      { id:"corporate-04", title:"Time Management for New Professionals", level:"foundational", shortDescription:"How to prioritize and manage workload early in a career.", learningObjective:"Learn foundational time and priority management approaches.", relatedTopicIds:["corporate-05","corporate-06"] },
      { id:"corporate-05", title:"Understanding Performance Reviews", level:"foundational", shortDescription:"How performance evaluation typically works and what it's meant to measure.", learningObjective:"Understand the purpose and structure of performance reviews.", relatedTopicIds:["corporate-04","corporate-09"] },
      { id:"corporate-06", title:"Managing Team Performance", level:"growth", shortDescription:"How managers set expectations and help a team meet them.", learningObjective:"Understand core approaches to managing team performance.", relatedTopicIds:["corporate-05","corporate-07"] },
      { id:"corporate-07", title:"Effective Delegation", level:"growth", shortDescription:"How to hand off work in a way that actually works.", learningObjective:"Learn principles of effective delegation.", relatedTopicIds:["corporate-06","corporate-14"] },
      { id:"corporate-08", title:"Navigating Office Politics", level:"growth", shortDescription:"How influence and relationships actually work inside organizations.", learningObjective:"Understand informal dynamics that shape organizational life.", relatedTopicIds:["corporate-03","corporate-13"] },
      { id:"corporate-09", title:"Building Cross-Functional Relationships", level:"growth", shortDescription:"How to work effectively with people outside your own team or department.", learningObjective:"Learn how to build influence across organizational boundaries.", relatedTopicIds:["corporate-03","corporate-05"] },
      { id:"corporate-10", title:"Giving and Receiving Feedback", level:"growth", shortDescription:"How to deliver and accept feedback in a way that actually improves performance.", learningObjective:"Understand principles of effective feedback.", relatedTopicIds:["corporate-06","corporate-13"] },
      { id:"corporate-11", title:"Organizational Design and Decision Rights", level:"advanced", shortDescription:"How companies structure themselves and decide who gets to decide what.", learningObjective:"Understand principles of organizational design.", relatedTopicIds:["corporate-01","corporate-15"] },
      { id:"corporate-12", title:"Change Management", level:"advanced", shortDescription:"How organizations plan and lead major transitions successfully.", learningObjective:"Understand frameworks for leading organizational change.", relatedTopicIds:["corporate-11","corporate-15"] },
      { id:"corporate-13", title:"Executive Presence and Influence", level:"advanced", shortDescription:"How senior leaders communicate and build credibility at scale.", learningObjective:"Understand what shapes executive presence and influence.", relatedTopicIds:["corporate-08","corporate-10"] },
      { id:"corporate-14", title:"Building High-Performing Teams", level:"advanced", shortDescription:"What separates high-performing teams from average ones.", learningObjective:"Understand the drivers of team performance at a senior level.", relatedTopicIds:["corporate-07","corporate-06"] },
      { id:"corporate-15", title:"Strategic Workforce Planning", level:"advanced", shortDescription:"How organizations plan for the talent and structure they'll need ahead of time.", learningObjective:"Understand the fundamentals of workforce planning.", relatedTopicIds:["corporate-11","corporate-12"] },
    ],
  },
  {
    id: "education",
    num: "03",
    label: "Education",
    tagline: "Learn how education systems and classrooms work, and how to grow as an educator or education leader.",
    topics: [
      { id:"education-01", title:"How the Education System Is Structured", level:"foundational", shortDescription:"The major components of how education is organized and governed.", learningObjective:"Understand the structure of the education system.", relatedTopicIds:["education-05","education-13"] },
      { id:"education-02", title:"Understanding Curriculum Design Basics", level:"foundational", shortDescription:"How curriculum is built around learning goals.", learningObjective:"Understand the fundamentals of curriculum design.", relatedTopicIds:["education-06","education-12"] },
      { id:"education-03", title:"Classroom Management Fundamentals", level:"foundational", shortDescription:"Core principles for creating a productive classroom environment.", learningObjective:"Learn foundational classroom management approaches.", relatedTopicIds:["education-10","education-04"] },
      { id:"education-04", title:"Understanding Learning Styles and Differentiation", level:"foundational", shortDescription:"How instruction can be adapted for different learners.", learningObjective:"Understand core concepts in differentiated instruction.", relatedTopicIds:["education-03","education-06"] },
      { id:"education-05", title:"Navigating Certification and Licensure", level:"foundational", shortDescription:"How teacher certification and licensure generally work.", learningObjective:"Understand the basics of certification pathways in education.", relatedTopicIds:["education-01","education-13"] },
      { id:"education-06", title:"Designing Effective Lesson Plans", level:"growth", shortDescription:"How to structure a lesson around clear objectives.", learningObjective:"Learn principles of effective lesson planning.", relatedTopicIds:["education-02","education-04"] },
      { id:"education-07", title:"Using Assessment Data to Guide Instruction", level:"growth", shortDescription:"How to use test and assignment data to adjust teaching.", learningObjective:"Understand how assessment data informs instruction.", relatedTopicIds:["education-09","education-12"] },
      { id:"education-08", title:"Building Relationships with Families", level:"growth", shortDescription:"How to communicate effectively with parents and guardians.", learningObjective:"Understand best practices for family engagement.", relatedTopicIds:["education-09","education-03"] },
      { id:"education-09", title:"Integrating Technology in the Classroom", level:"growth", shortDescription:"How to use technology to support learning without it becoming a distraction.", learningObjective:"Understand principles of effective educational technology use.", relatedTopicIds:["education-06","education-15"] },
      { id:"education-10", title:"Classroom Culture and Student Engagement", level:"growth", shortDescription:"How to build a classroom environment where students want to participate.", learningObjective:"Understand what drives engagement and classroom culture.", relatedTopicIds:["education-03","education-08"] },
      { id:"education-11", title:"Instructional Leadership", level:"advanced", shortDescription:"How education leaders support and elevate teaching quality across a school.", learningObjective:"Understand the role and practices of instructional leadership.", relatedTopicIds:["education-14","education-07"] },
      { id:"education-12", title:"Curriculum Development at Scale", level:"advanced", shortDescription:"How curriculum is designed and maintained across an entire school or district.", learningObjective:"Understand how curriculum development works at scale.", relatedTopicIds:["education-02","education-14"] },
      { id:"education-13", title:"Education Policy and Funding", level:"advanced", shortDescription:"How policy and funding decisions shape schools and classrooms.", learningObjective:"Understand the basics of education policy and funding structures.", relatedTopicIds:["education-01","education-05"] },
      { id:"education-14", title:"Building and Leading Academic Programs", level:"advanced", shortDescription:"How academic programs are designed, staffed, and evaluated.", learningObjective:"Understand how academic programs are built and led.", relatedTopicIds:["education-11","education-12"] },
      { id:"education-15", title:"Innovation in Educational Practice", level:"advanced", shortDescription:"How new teaching approaches and technologies get adopted in education.", learningObjective:"Understand how innovation happens within educational systems.", relatedTopicIds:["education-09","education-11"] },
    ],
  },
  {
    id: "realestate",
    num: "04",
    label: "Real Estate",
    tagline: "Learn how the real estate industry works, from your first transaction to advanced investment strategy.",
    topics: [
      { id:"realestate-01", title:"How the Real Estate Industry Works", level:"foundational", shortDescription:"The major players and how a typical real estate transaction flows.", learningObjective:"Understand the structure of the real estate industry.", relatedTopicIds:["realestate-04","realestate-05"] },
      { id:"realestate-02", title:"Your First Steps as a Real Estate Professional", level:"foundational", shortDescription:"What a new agent typically needs to understand and set up early on.", learningObjective:"Understand the early-career fundamentals of real estate work.", relatedTopicIds:["realestate-03","realestate-07"] },
      { id:"realestate-03", title:"Understanding Real Estate Licensing", level:"foundational", shortDescription:"How real estate licensing generally works.", learningObjective:"Understand the basics of real estate licensing requirements.", relatedTopicIds:["realestate-02","realestate-16"] },
      { id:"realestate-04", title:"Essential Real Estate Terminology", level:"foundational", shortDescription:"The vocabulary used every day in real estate transactions.", learningObjective:"Build familiarity with core real estate terminology.", relatedTopicIds:["realestate-01","realestate-05"] },
      { id:"realestate-05", title:"Understanding the Home Buying Process", level:"foundational", shortDescription:"The typical steps a buyer goes through from search to closing.", learningObjective:"Understand the stages of a home purchase.", relatedTopicIds:["realestate-04","realestate-12"] },
      { id:"realestate-06", title:"Understanding the Home Selling Process", level:"foundational", shortDescription:"The typical steps a seller goes through from listing to closing.", learningObjective:"Understand the stages of a home sale.", relatedTopicIds:["realestate-09","realestate-08"] },
      { id:"realestate-07", title:"Building a Client Pipeline", level:"growth", shortDescription:"How agents build a consistent flow of buyer and seller clients.", learningObjective:"Understand approaches to building a client pipeline.", relatedTopicIds:["realestate-02","realestate-11"] },
      { id:"realestate-08", title:"Real Estate Marketing Fundamentals", level:"growth", shortDescription:"How agents market themselves and their listings.", learningObjective:"Understand core real estate marketing approaches.", relatedTopicIds:["realestate-06","realestate-11"] },
      { id:"realestate-09", title:"Understanding Comps and Market Analysis", level:"growth", shortDescription:"How comparable sales are used to understand property value.", learningObjective:"Understand how comps inform pricing and valuation.", relatedTopicIds:["realestate-06","realestate-14"] },
      { id:"realestate-10", title:"Negotiation Fundamentals", level:"growth", shortDescription:"Core principles of negotiating in a real estate transaction.", learningObjective:"Understand foundational negotiation concepts for real estate.", relatedTopicIds:["realestate-05","realestate-06"] },
      { id:"realestate-11", title:"Building a Referral-Based Business", level:"growth", shortDescription:"How experienced agents grow largely through repeat and referral clients.", learningObjective:"Understand how referral-based business is built over time.", relatedTopicIds:["realestate-07","realestate-08"] },
      { id:"realestate-12", title:"Understanding Financing and Lending", level:"growth", shortDescription:"How mortgages and lending generally work in a transaction.", learningObjective:"Understand the basics of real estate financing.", relatedTopicIds:["realestate-05","realestate-15"] },
      { id:"realestate-13", title:"Building and Scaling a Real Estate Team", level:"advanced", shortDescription:"How top-producing agents build teams to scale their business.", learningObjective:"Understand the fundamentals of building a real estate team.", relatedTopicIds:["realestate-11","realestate-14"] },
      { id:"realestate-14", title:"Brokerage Economics and Operations", level:"advanced", shortDescription:"How brokerages make money and operate as businesses.", learningObjective:"Understand brokerage-level business fundamentals.", relatedTopicIds:["realestate-13","realestate-09"] },
      { id:"realestate-15", title:"Advanced Investment Strategy", level:"advanced", shortDescription:"How experienced investors evaluate and structure real estate deals.", learningObjective:"Understand advanced concepts in real estate investing.", relatedTopicIds:["realestate-12","realestate-16"] },
      { id:"realestate-16", title:"Risk, Ethics, and Compliance", level:"advanced", shortDescription:"Key risk, ethical, and compliance considerations in real estate practice.", learningObjective:"Understand core risk and compliance considerations in real estate.", relatedTopicIds:["realestate-03","realestate-15"] },
    ],
  },
  {
    id: "finance",
    num: "05",
    label: "Finance",
    tagline: "Learn how money, markets, and financial decisions work, from personal finance to advanced strategy.",
    topics: [
      { id:"finance-01", title:"How the Financial Industry Works", level:"foundational", shortDescription:"The major sectors and players that make up the financial industry.", learningObjective:"Understand the structure of the financial industry.", relatedTopicIds:["finance-11","finance-13"] },
      { id:"finance-02", title:"Personal Finance Fundamentals", level:"foundational", shortDescription:"The core building blocks of managing personal money well.", learningObjective:"Understand foundational personal finance concepts.", relatedTopicIds:["finance-03","finance-04"] },
      { id:"finance-03", title:"Understanding Credit and Debt", level:"foundational", shortDescription:"How credit works and how debt affects financial decisions.", learningObjective:"Understand the basics of credit and debt.", relatedTopicIds:["finance-02","finance-04"] },
      { id:"finance-04", title:"Budgeting Fundamentals", level:"foundational", shortDescription:"Core approaches to planning and tracking spending.", learningObjective:"Understand foundational budgeting approaches.", relatedTopicIds:["finance-02","finance-06"] },
      { id:"finance-05", title:"Understanding Investment Basics", level:"foundational", shortDescription:"The core concepts behind how investing works.", learningObjective:"Understand foundational investing concepts.", relatedTopicIds:["finance-07","finance-11"] },
      { id:"finance-06", title:"Building a Financial Plan", level:"growth", shortDescription:"How a financial plan connects goals, income, and decisions over time.", learningObjective:"Understand the components of a financial plan.", relatedTopicIds:["finance-04","finance-09"] },
      { id:"finance-07", title:"Understanding Risk and Diversification", level:"growth", shortDescription:"How risk and diversification shape investment decisions.", learningObjective:"Understand core risk and diversification concepts.", relatedTopicIds:["finance-05","finance-11"] },
      { id:"finance-08", title:"Tax Fundamentals for Individuals", level:"growth", shortDescription:"How personal income tax generally works.", learningObjective:"Understand foundational individual tax concepts.", relatedTopicIds:["finance-04","finance-06"] },
      { id:"finance-09", title:"Understanding Retirement Planning", level:"growth", shortDescription:"How retirement accounts and planning generally work.", learningObjective:"Understand the basics of retirement planning.", relatedTopicIds:["finance-06","finance-14"] },
      { id:"finance-10", title:"Reading Financial Statements", level:"growth", shortDescription:"How to read and understand basic financial statements.", learningObjective:"Understand the structure of core financial statements.", relatedTopicIds:["finance-12","finance-13"] },
      { id:"finance-11", title:"Portfolio Strategy and Asset Allocation", level:"advanced", shortDescription:"How experienced investors think about building a portfolio.", learningObjective:"Understand advanced portfolio strategy concepts.", relatedTopicIds:["finance-05","finance-07"] },
      { id:"finance-12", title:"Corporate Finance Fundamentals", level:"advanced", shortDescription:"How companies make financial decisions about capital and investment.", learningObjective:"Understand foundational corporate finance concepts.", relatedTopicIds:["finance-10","finance-13"] },
      { id:"finance-13", title:"Understanding Financial Markets and Instruments", level:"advanced", shortDescription:"How major financial markets and instruments function.", learningObjective:"Understand how financial markets and instruments work.", relatedTopicIds:["finance-01","finance-11"] },
      { id:"finance-14", title:"Wealth Management Strategy", level:"advanced", shortDescription:"How wealth management approaches long-term financial planning.", learningObjective:"Understand advanced wealth management concepts.", relatedTopicIds:["finance-09","finance-11"] },
      { id:"finance-15", title:"Regulatory and Compliance Considerations in Finance", level:"advanced", shortDescription:"Key regulatory and compliance considerations across the financial industry.", learningObjective:"Understand core regulatory concepts in finance.", relatedTopicIds:["finance-01","finance-12"] },
    ],
  },
  {
    id: "nonprofit",
    num: "06",
    label: "Nonprofit",
    tagline: "Learn how nonprofit organizations operate, fundraise, and grow their impact.",
    topics: [
      { id:"nonprofit-01", title:"How Nonprofit Organizations Work", level:"foundational", shortDescription:"The basic structure and purpose of a nonprofit organization.", learningObjective:"Understand how nonprofit organizations are structured.", relatedTopicIds:["nonprofit-02","nonprofit-05"] },
      { id:"nonprofit-02", title:"Understanding Nonprofit Structure and Governance", level:"foundational", shortDescription:"How nonprofit boards and governance generally work.", learningObjective:"Understand basic nonprofit governance structures.", relatedTopicIds:["nonprofit-01","nonprofit-12"] },
      { id:"nonprofit-03", title:"Introduction to Fundraising", level:"foundational", shortDescription:"The core approaches nonprofits use to raise money.", learningObjective:"Understand foundational fundraising concepts.", relatedTopicIds:["nonprofit-06","nonprofit-07"] },
      { id:"nonprofit-04", title:"Understanding Grant Funding", level:"foundational", shortDescription:"How grant funding generally works for nonprofits.", learningObjective:"Understand the basics of grant funding.", relatedTopicIds:["nonprofit-03","nonprofit-13"] },
      { id:"nonprofit-05", title:"Nonprofit Terminology and Compliance Basics", level:"foundational", shortDescription:"Key vocabulary and compliance concepts specific to nonprofits.", learningObjective:"Build familiarity with core nonprofit terminology.", relatedTopicIds:["nonprofit-01","nonprofit-02"] },
      { id:"nonprofit-06", title:"Donor Relationship Management", level:"growth", shortDescription:"How nonprofits build and maintain relationships with donors.", learningObjective:"Understand principles of donor relationship management.", relatedTopicIds:["nonprofit-03","nonprofit-10"] },
      { id:"nonprofit-07", title:"Building a Fundraising Campaign", level:"growth", shortDescription:"How a fundraising campaign is typically planned and run.", learningObjective:"Understand the structure of a fundraising campaign.", relatedTopicIds:["nonprofit-03","nonprofit-10"] },
      { id:"nonprofit-08", title:"Volunteer Program Management", level:"growth", shortDescription:"How nonprofits recruit, manage, and retain volunteers.", learningObjective:"Understand principles of volunteer program management.", relatedTopicIds:["nonprofit-09","nonprofit-14"] },
      { id:"nonprofit-09", title:"Measuring Program Impact", level:"growth", shortDescription:"How nonprofits track and demonstrate the impact of their work.", learningObjective:"Understand approaches to measuring program impact.", relatedTopicIds:["nonprofit-08","nonprofit-15"] },
      { id:"nonprofit-10", title:"Nonprofit Marketing and Storytelling", level:"growth", shortDescription:"How nonprofits communicate their mission to build support.", learningObjective:"Understand nonprofit marketing and storytelling approaches.", relatedTopicIds:["nonprofit-06","nonprofit-07"] },
      { id:"nonprofit-11", title:"Nonprofit Strategic Planning", level:"advanced", shortDescription:"How nonprofits set long-term direction and priorities.", learningObjective:"Understand strategic planning approaches for nonprofits.", relatedTopicIds:["nonprofit-12","nonprofit-15"] },
      { id:"nonprofit-12", title:"Board Governance and Development", level:"advanced", shortDescription:"How effective nonprofit boards are built and developed.", learningObjective:"Understand advanced board governance concepts.", relatedTopicIds:["nonprofit-02","nonprofit-11"] },
      { id:"nonprofit-13", title:"Diversifying Revenue Streams", level:"advanced", shortDescription:"How nonprofits reduce reliance on any single funding source.", learningObjective:"Understand approaches to nonprofit revenue diversification.", relatedTopicIds:["nonprofit-04","nonprofit-15"] },
      { id:"nonprofit-14", title:"Scaling Programs and Operations", level:"advanced", shortDescription:"How nonprofits grow their programs while maintaining quality.", learningObjective:"Understand considerations in scaling nonprofit operations.", relatedTopicIds:["nonprofit-08","nonprofit-09"] },
      { id:"nonprofit-15", title:"Nonprofit Financial Sustainability", level:"advanced", shortDescription:"How nonprofits build long-term financial resilience.", learningObjective:"Understand principles of nonprofit financial sustainability.", relatedTopicIds:["nonprofit-11","nonprofit-13"] },
    ],
  },
  {
    id: "wellness",
    num: "07",
    label: "Wellness",
    tagline: "Learn how the wellness industry works, and how to build and grow a wellness practice or career.",
    topics: [
      { id:"wellness-01", title:"How the Wellness Industry Works", level:"foundational", shortDescription:"The major sectors and career paths within the wellness industry.", learningObjective:"Understand the structure of the wellness industry.", relatedTopicIds:["wellness-02","wellness-04"] },
      { id:"wellness-02", title:"Understanding Different Wellness Career Paths", level:"foundational", shortDescription:"The range of roles and specialties within wellness work.", learningObjective:"Understand common wellness career paths.", relatedTopicIds:["wellness-01","wellness-04"] },
      { id:"wellness-03", title:"Foundations of Client Communication", level:"foundational", shortDescription:"Core principles for communicating with wellness clients.", learningObjective:"Understand foundational client communication skills.", relatedTopicIds:["wellness-06","wellness-08"] },
      { id:"wellness-04", title:"Understanding Certifications and Credentials", level:"foundational", shortDescription:"How certification generally works across wellness fields.", learningObjective:"Understand the basics of wellness certification pathways.", relatedTopicIds:["wellness-01","wellness-14"] },
      { id:"wellness-05", title:"Building Healthy Habits Fundamentals", level:"foundational", shortDescription:"The core principles behind how habits are formed and sustained.", learningObjective:"Understand foundational habit-formation concepts.", relatedTopicIds:["wellness-08","wellness-03"] },
      { id:"wellness-06", title:"Building a Client Base", level:"growth", shortDescription:"How wellness professionals grow a consistent base of clients.", learningObjective:"Understand approaches to building a client base.", relatedTopicIds:["wellness-03","wellness-10"] },
      { id:"wellness-07", title:"Program and Session Design", level:"growth", shortDescription:"How to structure sessions or programs around client goals.", learningObjective:"Understand principles of program and session design.", relatedTopicIds:["wellness-05","wellness-08"] },
      { id:"wellness-08", title:"Understanding Behavior Change Principles", level:"growth", shortDescription:"How behavior change actually happens, and what supports it.", learningObjective:"Understand core behavior change principles.", relatedTopicIds:["wellness-05","wellness-07"] },
      { id:"wellness-09", title:"Wellness Business Models", level:"growth", shortDescription:"The common ways wellness professionals structure their business.", learningObjective:"Understand common wellness business models.", relatedTopicIds:["wellness-06","wellness-11"] },
      { id:"wellness-10", title:"Marketing a Wellness Practice", level:"growth", shortDescription:"How wellness professionals market themselves authentically.", learningObjective:"Understand core wellness marketing approaches.", relatedTopicIds:["wellness-06","wellness-15"] },
      { id:"wellness-11", title:"Scaling a Wellness Business", level:"advanced", shortDescription:"How wellness practitioners grow beyond one-on-one work.", learningObjective:"Understand approaches to scaling a wellness business.", relatedTopicIds:["wellness-09","wellness-12"] },
      { id:"wellness-12", title:"Building Group Programs and Retreats", level:"advanced", shortDescription:"How group programs and retreats are typically designed and run.", learningObjective:"Understand the fundamentals of group program design.", relatedTopicIds:["wellness-07","wellness-11"] },
      { id:"wellness-13", title:"Wellness Industry Trends and Innovation", level:"advanced", shortDescription:"How the wellness industry is evolving and where it's headed.", learningObjective:"Understand current trends shaping the wellness industry.", relatedTopicIds:["wellness-01","wellness-15"] },
      { id:"wellness-14", title:"Ethics and Scope of Practice", level:"advanced", shortDescription:"Key ethical and scope-of-practice considerations in wellness work.", learningObjective:"Understand core ethical considerations in wellness practice.", relatedTopicIds:["wellness-04","wellness-03"] },
      { id:"wellness-15", title:"Building Strategic Partnerships in Wellness", level:"advanced", shortDescription:"How wellness professionals build valuable partnerships and collaborations.", learningObjective:"Understand how strategic partnerships work in wellness.", relatedTopicIds:["wellness-10","wellness-13"] },
    ],
  },
  {
    id: "creative",
    num: "08",
    label: "Creative & Media",
    tagline: "Learn how creative careers and businesses work, from your first portfolio to scaling a creative team.",
    topics: [
      { id:"creative-01", title:"How the Creative Industry Works", level:"foundational", shortDescription:"The major paths and structures within creative and media work.", learningObjective:"Understand the structure of the creative industry.", relatedTopicIds:["creative-02","creative-03"] },
      { id:"creative-02", title:"Building a Portfolio", level:"foundational", shortDescription:"How a strong creative portfolio is put together.", learningObjective:"Understand principles of effective portfolio building.", relatedTopicIds:["creative-01","creative-09"] },
      { id:"creative-03", title:"Understanding Creative Business Models", level:"foundational", shortDescription:"The common ways creative professionals structure how they earn.", learningObjective:"Understand common creative business models.", relatedTopicIds:["creative-04","creative-11"] },
      { id:"creative-04", title:"Pricing Creative Work", level:"foundational", shortDescription:"How creative professionals think about pricing their work.", learningObjective:"Understand foundational pricing approaches for creative work.", relatedTopicIds:["creative-03","creative-10"] },
      { id:"creative-05", title:"Copyright and Ownership Basics", level:"foundational", shortDescription:"How copyright and ownership generally work for creative work.", learningObjective:"Understand foundational copyright and ownership concepts.", relatedTopicIds:["creative-10","creative-13"] },
      { id:"creative-06", title:"Building a Personal Brand", level:"growth", shortDescription:"How creative professionals build a recognizable identity.", learningObjective:"Understand principles of personal brand building.", relatedTopicIds:["creative-07","creative-08"] },
      { id:"creative-07", title:"Growing an Audience", level:"growth", shortDescription:"How creative professionals build and grow an audience over time.", learningObjective:"Understand core approaches to audience growth.", relatedTopicIds:["creative-06","creative-08"] },
      { id:"creative-08", title:"Understanding Content Strategy", level:"growth", shortDescription:"How a content strategy connects goals to what gets created and shared.", learningObjective:"Understand the basics of content strategy.", relatedTopicIds:["creative-06","creative-07"] },
      { id:"creative-09", title:"Pitching and Landing Clients", level:"growth", shortDescription:"How creative professionals pitch their work and win clients.", learningObjective:"Understand core principles of pitching creative work.", relatedTopicIds:["creative-02","creative-04"] },
      { id:"creative-10", title:"Negotiating Creative Contracts", level:"growth", shortDescription:"What to understand before signing a creative work agreement.", learningObjective:"Understand foundational contract negotiation concepts for creative work.", relatedTopicIds:["creative-04","creative-05"] },
      { id:"creative-11", title:"Building Multiple Revenue Streams", level:"advanced", shortDescription:"How experienced creatives diversify how they earn.", learningObjective:"Understand approaches to diversifying creative income.", relatedTopicIds:["creative-03","creative-12"] },
      { id:"creative-12", title:"Scaling a Creative Business or Studio", level:"advanced", shortDescription:"How creative businesses grow beyond one person doing the work.", learningObjective:"Understand considerations in scaling a creative business.", relatedTopicIds:["creative-11","creative-15"] },
      { id:"creative-13", title:"Brand Partnerships and Licensing", level:"advanced", shortDescription:"How brand partnerships and licensing deals typically work.", learningObjective:"Understand the fundamentals of brand partnerships and licensing.", relatedTopicIds:["creative-05","creative-11"] },
      { id:"creative-14", title:"Creative Industry Trends and Technology", level:"advanced", shortDescription:"How new technology and trends are shaping creative work.", learningObjective:"Understand current trends shaping the creative industry.", relatedTopicIds:["creative-01","creative-08"] },
      { id:"creative-15", title:"Building a Creative Team", level:"advanced", shortDescription:"How creative professionals build and lead a team around their work.", learningObjective:"Understand the fundamentals of building a creative team.", relatedTopicIds:["creative-12","creative-14"] },
    ],
  },
];

export function findLearningTopic(topicId) {
  for (const cat of LEARNING_HUB) {
    const topic = cat.topics.find(t => t.id === topicId);
    if (topic) return { topic, category: cat };
  }
  return null;
}
